### PR TITLE
Rpmfusion fixes

### PR DESCRIPTION
**Pull request by kwizart**
- Re-introduce Conflicts - rfbz#6612
- Enforces version to avoid miss-match with fedora

### CODE REVIEW

**Comment by kparal** [comment]
The Conflict change looks fine. The `mesa-filesystem` requirement caused issues for me today, see https://bugzilla.rpmfusion.org/show_bug.cgi?id=6641 .

**Comment by kparal** [comment]
I've tested this patch together with a Fedora patch and it works fine for me. See https://src.fedoraproject.org/rpms/mesa/pull-request/20#comment-137898

**Comment by joshua-stone** [comment]
Is there anything that can be done to improve communication between Fedora and RPMFusion for handling the mesa packages?

We've had to omit mesa-va-freeworld from F38 for a while due to an issue that was very similar to this. Adding it to F38 was working for a time before it broke again shortly between F38 GA and had to disable it once more for builds to pass:

https://github.com/ublue-os/main/pull/21
https://github.com/ublue-os/main/pull/67
https://github.com/ublue-os/main/pull/163

**Comment by dnkmmr69420** [comment]
There should be better communication between Fedora and RPMFusion

**Pull request merged**
